# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  paymentdb:
    image: postgres
    container_name: paymentdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=PaymentTestDb
    volumes:
      - paymentdb_volume:/var/lib/postgresql/data
  paymentseq:
    image: datalust/seq
    container_name: paymentseq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - paymentseq_volume:/data
    ports:
      - 5341:80
  paymentapplyprojectweb:
    image: paymentapplyprojectweb
    container_name: paymentapplyprojectweb
    restart: always
    build:
      context: .
      dockerfile: PaymentApplyProject.Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ConnectionStrings:DefaultConnection=User ID=admin;Password=12345678;Host=paymentdb;Port=5432;Database=PaymentTestDb;Pooling=true;
      - SeqSettings:ServerUrl=http://paymentseq:5341
    depends_on:
      - paymentdb
  paymentapplyprojectwebtest:
    image: paymentapplyprojectwebtest
    container_name: paymentapplyprojectwebtest
    restart: always
    build:
      context: .
      dockerfile: PaymentApplyProject.Web/Dockerfile
    ports:
      - 5010:80
      - 5011:443
    environment:
      - ConnectionStrings:DefaultConnection=User ID=admin;Password=12345678;Host=paymentdb;Port=5432;Database=PaymentTestDb;Pooling=true;
      - SeqSettings:ServerUrl=http://paymentseq:5341
    depends_on:
      - paymentdb
volumes:
  paymentdb_volume:
  paymentseq_volume: