//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentApplyProject.Application.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PaymentApplyProject.Application.Localizations.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authenticated user does not have a valid company..
        /// </summary>
        public static string AuthenticatedUserHaveNoValidCompany {
            get {
                return ResourceManager.GetString("AuthenticatedUserHaveNoValidCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı hesap numarasına sahip kayıt mevcut..
        /// </summary>
        public static string AyniHesapNumarasinaSahipKayitVar {
            get {
                return ResourceManager.GetString("AyniHesapNumarasinaSahipKayitVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adına sahip kullanıcı mevcut..
        /// </summary>
        public static string AyniKullaniciAdinaSahipKayitVar {
            get {
                return ResourceManager.GetString("AyniKullaniciAdinaSahipKayitVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu email adresine sahip kullanıcı mevcut..
        /// </summary>
        public static string AyniMailAdresineSahipKayitVar {
            get {
                return ResourceManager.GetString("AyniMailAdresineSahipKayitVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcutta bekleyen işlem vardır..
        /// </summary>
        public static string BekleyenIslemVar {
            get {
                return ResourceManager.GetString("BekleyenIslemVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu banka için bu aralıkta kayıt mevcut..
        /// </summary>
        public static string BuAraliktaBankaHesabiVar {
            get {
                return ResourceManager.GetString("BuAraliktaBankaHesabiVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company is not active..
        /// </summary>
        public static string CompanyIsNotActive {
            get {
                return ResourceManager.GetString("CompanyIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your company is not found..
        /// </summary>
        public static string CompanyIsNotFound {
            get {
                return ResourceManager.GetString("CompanyIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer is not active..
        /// </summary>
        public static string CustomerIsNotActive {
            get {
                return ResourceManager.GetString("CustomerIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is not found..
        /// </summary>
        public static string CustomerIsNotFound {
            get {
                return ResourceManager.GetString("CustomerIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit is not found..
        /// </summary>
        public static string DepositIsNotFound {
            get {
                return ResourceManager.GetString("DepositIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This deposit request was used..
        /// </summary>
        public static string DepositRequestHashIsUsed {
            get {
                return ResourceManager.GetString("DepositRequestHashIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit request is not found..
        /// </summary>
        public static string DepositRequestIsNotFound {
            get {
                return ResourceManager.GetString("DepositRequestIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit request is timeout..
        /// </summary>
        public static string DepositRequestIsTimeout {
            get {
                return ResourceManager.GetString("DepositRequestIsTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş bilgileriniz yanlıştır..
        /// </summary>
        public static string GirisBilgisiYanlis {
            get {
                return ResourceManager.GetString("GirisBilgisiYanlis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarılı..
        /// </summary>
        public static string IslemBasarili {
            get {
                return ResourceManager.GetString("IslemBasarili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key is null..
        /// </summary>
        public static string KeyValueIsNull {
            get {
                return ResourceManager.GetString("KeyValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu müşteriye işlemler kapalıdır..
        /// </summary>
        public static string MusteriyeIslemlerKapali {
            get {
                return ResourceManager.GetString("MusteriyeIslemlerKapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not authenticated..
        /// </summary>
        public static string NotAuthenticated {
            get {
                return ResourceManager.GetString("NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıt onaylanmış..
        /// </summary>
        public static string Onaylanmis {
            get {
                return ResourceManager.GetString("Onaylanmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kayıt reddedilmiş..
        /// </summary>
        public static string Reddedilmis {
            get {
                return ResourceManager.GetString("Reddedilmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a deposit with the same transaction ID..
        /// </summary>
        public static string ThereIsDepositSameTransactionId {
            get {
                return ResourceManager.GetString("ThereIsDepositSameTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pending deposit. You cannot create a new transaction until this one has ended..
        /// </summary>
        public static string ThereIsPendingDeposit {
            get {
                return ResourceManager.GetString("ThereIsPendingDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pending transaction..
        /// </summary>
        public static string ThereIsPendingTransaction {
            get {
                return ResourceManager.GetString("ThereIsPendingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a pending withdraw. You cannot create a new transaction until this one has ended..
        /// </summary>
        public static string ThereIsPendingWithdraw {
            get {
                return ResourceManager.GetString("ThereIsPendingWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a withdraw with the same transaction ID..
        /// </summary>
        public static string ThereIsWithdrawSameTransactionId {
            get {
                return ResourceManager.GetString("ThereIsWithdrawSameTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Successful.
        /// </summary>
        public static string TransactionSuccessful {
            get {
                return ResourceManager.GetString("TransactionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has no authorization..
        /// </summary>
        public static string UserHasNoAuthorization {
            get {
                return ResourceManager.GetString("UserHasNoAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has no company..
        /// </summary>
        public static string UserHasNoCompany {
            get {
                return ResourceManager.GetString("UserHasNoCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri bulunamadı..
        /// </summary>
        public static string VeriBulunamadi {
            get {
                return ResourceManager.GetString("VeriBulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw is not found..
        /// </summary>
        public static string WithdrawIsNotFound {
            get {
                return ResourceManager.GetString("WithdrawIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sisteme giriş için yetkiniz yok..
        /// </summary>
        public static string YetkinizYok {
            get {
                return ResourceManager.GetString("YetkinizYok", resourceCulture);
            }
        }
    }
}
